INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (1, 8);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (1, 15);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (1, 17);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (2, 2);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (2, 8);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (2, 19);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (3, 15);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (4, 15);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (4, 17);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (5, 4);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (5, 14);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (6, 8);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (6, 13);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (7, 1);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (7, 22);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (8, 15);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (9, 1);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (9,15);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (9,21);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (10,8);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (10, 13);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (11, 2);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (11, 9);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (11, 17);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (12, 15);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (13, 2);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (13, 13);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (13, 17);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (14, 22);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (15, 13);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (16, 4);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (16,17);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (17,15);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (18, 15);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (19, 12);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (19, 22);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (20, 2);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (20, 22);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (21, 9);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (21, 22);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (22, 9);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (23, 22);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (24, 9);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (25, 12);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (25, 22);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (26, 22);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (27, 22);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (28, 1);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (29, 1);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (29, 4);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (30, 21);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (31, 21);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (32, 22);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (32, 4);
INSERT INTO  hobby_gift (id_gift, id_hobby) VALUES (32, 8);
